kind: Service
apiVersion: v1
metadata:
  name: dans-ruby-app
spec:
  selector:
    app: ruby-app
  ports:
    - protocol: TCP
      nodePort: 30211
      port: 3000
      targetPort: 3000
  type: NodePort
